#!/usr/bin/env python3
"""Concatenate files and run the cool interpreter on the result."""
import sys
import os

tmp_file = '_tmp.cl'
standard_libs = ['./libs/atoi.cl']

files = sys.argv[1:]
files.extend(standard_libs)

command = 'cat {} > {}'.format(' '.join(files), tmp_file)
os.system(command)
os.system('cool_interpreter {}'.format(tmp_file))
os.system('rm {}'.format(tmp_file))
